# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FYAD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
#  pod 'AFNetworking', '> 2.6.2'
#  pod 'SDWebImage', '~>3.7'
#  pod 'BlocksKit'
  pod 'FYAD','1.0.1.2'

  # Pods for FYAD

end
